"""
Author: Tolet-Now
All response status
"""
from django.utils.translation import gettext as _

# status code for authentication
ACCOUNT_ACTIVATION_TOKEN_INVALID = _("AATI4001")
EXPIRED_SIGNATURE = _("ES3041")
EXPIRED_REFRESH = _("ER3041")
REQUIRED_ORIGIN_IAT_FIELD = _("ROIF3042")
SIGNATURE_DECODE_ERROR = _("SDE4001")
INVALID_PAYLOAD = _("IP3042")
INVALID_USER = _("IU3042")
DISABLED_USER_ACCOUNT = _("DUA3041")

# status code for general user
USER_ACCOUNT_CREATED = _("UAC2011")
USER_FIELD_REQUIRED = _("UFR4001")
USER_ACCOUNT_ACTIVATED = _("UAA2021")
USER_PROFILE_FOUND = _("UPF2001")
USER_PROFILE_NOT_FOUND = _("UPNF4001")
USER_UPDATED = _("UU2001")
USER_MISMATCH = _("UMM4001")
USER_USERNAME_UPDATED = _("UUU2011")
USER_USERNAME_CONFLICT = _("UUC4001")
USER_USERNAME_NOT_MODIFIED = _("UUNM3041")
USER_EMAIL_UPDATED = _("UEU2012")
USER_PASSWORD_UPDATED = _("UPU2013")
USER_EMAIL_CONFLICT = _("UEC4002")
USER_EMAIL_NOT_MODIFIED = _("UENM3042")
USER_KEY_ERROR = _("UKE4001")

# status code for follow user
USER_NOT_FOUND = _("UNF4001")
UNAUTHENTICATED_USER = _("UU4002")
